version: '3.8'

services:
  book_service:
    build: ./book_service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./book_service/:/app/
    ports:
      - 8001:8000
    environment:
      - DATABASE_URI=postgresql://book_db_username:book_db_password@book_db/book_db_test
      - PUBLISHER_HOST_URL=http://publisher_service:8000/api/v1/publishers/

  book_db:
    image: postgres:12
    volumes:
      - postgres_data_book:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=book_db_username
      - POSTGRES_PASSWORD=book_db_password
      - POSTGRES_DB=book_db_test

  publisher_service:
    build: ./publisher_service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./publisher_service/:/app/
    ports:
      - 8002:8000
    environment:
      - DATABASE_URI=postgresql://publisher_db_username:publisher_db_password@publisher_db/publisher_db_test
  
  publisher_db:
    image: postgres:12
    volumes:
      - postgres_data_publisher:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=publisher_db_username
      - POSTGRES_PASSWORD=publisher_db_password
      - POSTGRES_DB=publisher_db_test

  nginx:
    image: nginx
    ports:
      - '8080:8080'
    volumes:
      - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - book_service
      - publisher_service

volumes:
  postgres_data_book:
  postgres_data_publisher: